import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { TreeNode, Method } from '../../../data/knowledgeTreeData';
import { X, FileText, Star, AlertCircle, Link2, Edit, Download } from 'lucide-react';
import { Button } from '../ui/button';
import { ScrollArea } from '../ui/scroll-area';
import { Badge } from '../ui/badge';
import { Separator } from '../ui/separator';

interface NodeDetailPanelProps {
  node: TreeNode | null;
  onClose: () => void;
  onLinkNode: () => void;
  onEditNode: () => void;
  onExportNode: () => void;
  onViewPaper: (paperId: string) => void;
}

export function NodeDetailPanel({ 
  node, 
  onClose, 
  onLinkNode, 
  onEditNode, 
  onExportNode,
  onViewPaper 
}: NodeDetailPanelProps) {
  if (!node) return null;

  const getMaturityStars = (level: number) => {
    return '⭐'.repeat(level) + '☆'.repeat(5 - level);
  };

  const getStatusLabel = (status: Method['status']) => {
    const labels = {
      exploratory: 'Exploratory',
      'clinical-trials': 'Clinical Trials',
      'clinical-practice': 'Clinical Practice',
      established: 'Established'
    };
    return labels[status];
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ x: '100%' }}
        animate={{ x: 0 }}
        exit={{ x: '100%' }}
        transition={{ type: 'spring', damping: 25, stiffness: 200 }}
        className="fixed right-0 top-0 h-full w-[480px] bg-white border-l border-gray-200 shadow-2xl z-50"
      >
        <div className="flex flex-col h-full">
          {/* Header */}
          <div className="flex items-start justify-between p-6 border-b border-gray-200">
            <div className="flex-1 pr-4">
              <Button
                variant="ghost"
                size="sm"
                onClick={onClose}
                className="mb-2 -ml-2"
              >
                <X className="w-4 h-4 mr-1" />
                Back to Tree
              </Button>
              <h2 className="text-xl font-semibold">{node.title}</h2>
              <div className="flex items-center gap-2 mt-2">
                {node.isFoundational && (
                  <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-300">
                    <Star className="w-3 h-3 mr-1" />
                    Foundational
                  </Badge>
                )}
                <Badge variant="outline">
                  {node.autoGenerated ? '🤖 Auto-generated' : '✏️ Manual'}
                </Badge>
              </div>
            </div>
          </div>

          {/* Content */}
          <ScrollArea className="flex-1">
            <div className="p-6 space-y-6">
              {/* WHAT Section */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-2xl">📊</span>
                  <h3 className="font-semibold text-lg">WHAT is the problem?</h3>
                </div>
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                  <p className="text-gray-800 leading-relaxed">{node.what}</p>
                  <p className="text-sm text-gray-600 mt-3">
                    From {node.paperCount} {node.paperCount === 1 ? 'paper' : 'papers'} in your library
                  </p>
                </div>
              </div>

              {/* WHY Section */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-2xl">🔵</span>
                  <h3 className="font-semibold text-lg">WHY does it matter?</h3>
                </div>
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                  <p className="text-gray-800 leading-relaxed whitespace-pre-line">{node.why}</p>
                </div>
              </div>

              {/* HOW Section */}
              {node.how.length > 0 && (
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-2xl">🟢</span>
                    <h3 className="font-semibold text-lg">HOW are researchers solving this?</h3>
                  </div>
                  <div className="space-y-4">
                    {node.how.map((method, index) => (
                      <div key={method.id} className="bg-green-50 border border-green-200 rounded-lg p-4">
                        <div className="flex items-start justify-between mb-2">
                          <div>
                            <h4 className="font-semibold text-gray-900">
                              Method {index + 1}: {method.name}
                            </h4>
                            <p className="text-sm text-gray-600 mt-1">Type: {method.type}</p>
                          </div>
                        </div>
                        
                        <div className="space-y-2 mt-3">
                          <div className="flex items-center gap-2 text-sm">
                            <span className="font-medium text-gray-700">Status:</span>
                            <Badge variant="secondary">{getStatusLabel(method.status)}</Badge>
                            <span className="ml-2">{getMaturityStars(method.maturityLevel)}</span>
                          </div>
                          
                          <div className="text-sm">
                            <span className="font-medium text-gray-700">Papers:</span>
                            <span className="ml-2 text-blue-600 cursor-pointer hover:underline">
                              View {method.paperIds.length} {method.paperIds.length === 1 ? 'paper' : 'papers'}
                            </span>
                          </div>

                          {method.effectiveness && (
                            <div className="text-sm">
                              <span className="font-medium text-gray-700">Effectiveness:</span>
                              <p className="text-gray-800 mt-1">{method.effectiveness}</p>
                            </div>
                          )}

                          {method.limitations && (
                            <div className="text-sm">
                              <span className="font-medium text-gray-700">Limitations:</span>
                              <p className="text-gray-800 mt-1">{method.limitations}</p>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* GAPS Section */}
              {node.gaps.length > 0 && (
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-2xl">🔴</span>
                    <h3 className="font-semibold text-lg">GAPS & CONTROVERSIES</h3>
                  </div>
                  <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                    <ul className="space-y-2">
                      {node.gaps.map((gap, index) => (
                        <li key={index} className="flex items-start gap-2 text-gray-800">
                          <AlertCircle className="w-4 h-4 text-red-600 mt-0.5 flex-shrink-0" />
                          <span>{gap}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

              <Separator />

              {/* Contributing Papers */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <FileText className="w-5 h-5 text-gray-600" />
                  <h3 className="font-semibold text-lg">
                    Contributing Papers ({node.paperCount})
                  </h3>
                </div>
                <div className="space-y-3">
                  {node.paperIds.slice(0, 5).map((paperId, index) => (
                    <div 
                      key={paperId}
                      className="bg-gray-50 border border-gray-200 rounded-lg p-3 hover:bg-gray-100 transition-colors"
                    >
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <p className="font-medium text-gray-900 text-sm">
                            {index === 0 ? 'Smith 2023 - Plasma p-tau for early AD' : 
                             index === 1 ? 'Chen 2022 - Blood biomarkers validation' : 
                             index === 2 ? 'Brown 2024 - NfL in clinical practice' :
                             index === 3 ? 'Lee 2021 - Multi-biomarker approach' :
                             'Wang 2023 - Machine learning integration'}
                          </p>
                          <div className="flex items-center gap-2 mt-1">
                            <Badge variant="outline" className="text-xs">
                              {index < 2 ? 'Methods' : index < 4 ? 'Knowledge' : 'Conclusion'}
                            </Badge>
                            <span className="text-xs text-gray-600">
                              Relevance: {90 - index * 2}
                            </span>
                          </div>
                        </div>
                        <Button 
                          variant="outline" 
                          size="sm"
                          onClick={() => onViewPaper(paperId)}
                        >
                          Read
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* User Notes */}
              {node.userNotes && (
                <div>
                  <h3 className="font-semibold mb-2">My Notes</h3>
                  <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                    <p className="text-gray-800">{node.userNotes}</p>
                  </div>
                </div>
              )}
            </div>
          </ScrollArea>

          {/* Footer Actions */}
          <div className="border-t border-gray-200 p-4 space-y-2">
            <div className="grid grid-cols-2 gap-2">
              <Button variant="outline" size="sm" onClick={onLinkNode}>
                <Link2 className="w-4 h-4 mr-1" />
                Link to Node
              </Button>
              <Button variant="outline" size="sm" onClick={onEditNode}>
                <Edit className="w-4 h-4 mr-1" />
                Edit Summary
              </Button>
            </div>
            <Button variant="outline" size="sm" className="w-full" onClick={onExportNode}>
              <Download className="w-4 h-4 mr-1" />
              Export Node
            </Button>
          </div>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}
