export type NodeType = 'problem' | 'solution' | 'mechanism' | 'gap';

export type ConnectionType = 'complementary' | 'sequential' | 'alternative' | 'contradictory';

export interface TreeNode {
  id: string;
  title: string;
  type: NodeType;
  parentId: string | null;
  position: { x: number; y: number };
  paperCount: number;
  paperIds: string[]; // references to paper IDs
  
  // Content sections
  what: string;
  why: string;
  how: Method[];
  gaps: string[];
  
  // Metadata
  createdAt: string;
  lastUpdated: string;
  isFoundational: boolean;
  autoGenerated: boolean;
  userNotes?: string;
}

export interface Method {
  id: string;
  name: string;
  type: string;
  status: 'exploratory' | 'clinical-trials' | 'clinical-practice' | 'established';
  maturityLevel: 1 | 2 | 3 | 4 | 5; // stars
  paperIds: string[];
  effectiveness?: string;
  limitations?: string;
}

export interface TreeConnection {
  id: string;
  fromNodeId: string;
  toNodeId: string;
  type: ConnectionType;
  explanation: string;
  evidencePaperIds: string[];
  strength: 'weak' | 'moderate' | 'strong';
}

export interface KnowledgeTree {
  id: string;
  projectId: string;
  projectName: string;
  nodes: TreeNode[];
  connections: TreeConnection[];
  mainBranches: string[]; // node IDs that are main branches
  lastBuilt: string;
  autoUpdate: boolean;
  buildFromFullText: boolean;
}

export interface TreeSettings {
  autoUpdate: boolean;
  buildFromAbstracts: boolean;
  buildFromCitations: boolean;
  buildFromHighlights: boolean;
  buildFromFullText: boolean;
  enabledBranches: string[];
  minPapersForSubBranch: number;
  autoDetectRelationships: boolean;
  autoIdentifyGaps: boolean;
  suggestCrossLinks: boolean;
  flagContradictions: boolean;
  aiConfidenceThreshold: 'low' | 'medium' | 'high';
  showLabels: 'always' | 'hover' | 'click';
  showPaperCounts: boolean;
}

// Mock data for demonstration
export const mockKnowledgeTree: KnowledgeTree = {
  id: 'kt1',
  projectId: 'p1',
  projectName: 'Thesis Chapter 2',
  lastBuilt: '2024-01-15T10:30:00',
  autoUpdate: true,
  buildFromFullText: false,
  mainBranches: ['node1', 'node2', 'node3'],
  nodes: [
    {
      id: 'root',
      title: "Alzheimer's Disease Research",
      type: 'problem',
      parentId: null,
      position: { x: 400, y: 50 },
      paperCount: 12,
      paperIds: ['pp1', 'pp2', 'pp3', 'pp4', 'pp5', 'pp6', 'pp7', 'pp8', 'pp9', 'pp10', 'pp11', 'pp12'],
      what: "Progressive neurodegenerative disorder affecting memory, thinking, and behavior",
      why: "Leading cause of dementia worldwide, affecting 50 million people globally",
      how: [],
      gaps: [],
      createdAt: '2024-01-10T10:00:00',
      lastUpdated: '2024-01-15T10:30:00',
      isFoundational: true,
      autoGenerated: true
    },
    {
      id: 'node1',
      title: 'Biology & Pathophysiology',
      type: 'mechanism',
      parentId: 'root',
      position: { x: 200, y: 200 },
      paperCount: 5,
      paperIds: ['pp1', 'pp2', 'pp3', 'pp4', 'pp5'],
      what: "Understanding the biological mechanisms underlying Alzheimer's disease progression",
      why: "Critical for developing targeted therapies and early detection methods",
      how: [],
      gaps: ['Exact trigger mechanisms unclear', 'Role of genetics vs environment debated'],
      createdAt: '2024-01-10T10:00:00',
      lastUpdated: '2024-01-15T10:30:00',
      isFoundational: true,
      autoGenerated: true
    },
    {
      id: 'node2',
      title: 'Diagnosis & Detection',
      type: 'solution',
      parentId: 'root',
      position: { x: 400, y: 200 },
      paperCount: 4,
      paperIds: ['pp6', 'pp7', 'pp8', 'pp9'],
      what: "Methods and technologies for early and accurate diagnosis of Alzheimer's disease",
      why: "Early diagnosis enables timely intervention and better patient outcomes",
      how: [],
      gaps: ['Cost-effective screening methods needed', 'Accuracy in early stages limited'],
      createdAt: '2024-01-10T10:00:00',
      lastUpdated: '2024-01-15T10:30:00',
      isFoundational: false,
      autoGenerated: true
    },
    {
      id: 'node3',
      title: 'Treatment & Therapies',
      type: 'solution',
      parentId: 'root',
      position: { x: 600, y: 200 },
      paperCount: 3,
      paperIds: ['pp10', 'pp11', 'pp12'],
      what: "Therapeutic interventions to slow progression or manage symptoms",
      why: "Current treatments only address symptoms; disease-modifying therapies urgently needed",
      how: [],
      gaps: ['Limited effectiveness of current drugs', 'No cure available yet'],
      createdAt: '2024-01-10T10:00:00',
      lastUpdated: '2024-01-15T10:30:00',
      isFoundational: false,
      autoGenerated: true
    },
    {
      id: 'node1-1',
      title: 'Amyloid Plaques',
      type: 'mechanism',
      parentId: 'node1',
      position: { x: 120, y: 350 },
      paperCount: 5,
      paperIds: ['pp1', 'pp2', 'pp3', 'pp4', 'pp5'],
      what: "Abnormal protein clusters that accumulate between neurons, disrupting cell function",
      why: "Amyloid beta accumulation is one of the earliest pathological changes in AD, occurring 10-20 years before symptoms. Associated with synaptic dysfunction and neuronal death.",
      how: [
        {
          id: 'm1',
          name: 'Anti-amyloid antibodies',
          type: 'Immunotherapy',
          status: 'clinical-trials',
          maturityLevel: 4,
          paperIds: ['pp1', 'pp2'],
          effectiveness: 'Aducanumab and lecanemab show 27% slower cognitive decline',
          limitations: 'Risk of brain swelling (ARIA), high cost, requires early intervention'
        },
        {
          id: 'm2',
          name: 'BACE inhibitors',
          type: 'Small molecule drugs',
          status: 'clinical-trials',
          maturityLevel: 3,
          paperIds: ['pp3'],
          effectiveness: 'Reduces amyloid production by 50-70% in animal models',
          limitations: 'Phase 3 trials discontinued due to cognitive worsening'
        }
      ],
      gaps: [
        'Unclear if amyloid is cause or consequence',
        'Removal does not always improve cognition',
        'Optimal timing of intervention unknown'
      ],
      createdAt: '2024-01-10T10:00:00',
      lastUpdated: '2024-01-15T10:30:00',
      isFoundational: true,
      autoGenerated: true
    },
    {
      id: 'node1-2',
      title: 'Tau Tangles',
      type: 'mechanism',
      parentId: 'node1',
      position: { x: 280, y: 350 },
      paperCount: 4,
      paperIds: ['pp2', 'pp3', 'pp4', 'pp5'],
      what: "Twisted protein fibers that build up inside neurons, disrupting cell transport",
      why: "Tau pathology correlates more strongly with cognitive decline than amyloid. Spreads through connected neurons in a prion-like manner.",
      how: [
        {
          id: 'm3',
          name: 'Tau aggregation inhibitors',
          type: 'Small molecule drugs',
          status: 'clinical-trials',
          maturityLevel: 3,
          paperIds: ['pp4'],
          effectiveness: 'Reduced tau aggregation in vitro',
          limitations: 'Limited brain penetration, mixed clinical trial results'
        }
      ],
      gaps: [
        'Mechanisms of tau spreading not fully understood',
        'No approved tau-targeting therapies yet'
      ],
      createdAt: '2024-01-10T10:00:00',
      lastUpdated: '2024-01-15T10:30:00',
      isFoundational: true,
      autoGenerated: true
    },
    {
      id: 'node2-1',
      title: 'Blood Biomarkers',
      type: 'solution',
      parentId: 'node2',
      position: { x: 340, y: 350 },
      paperCount: 3,
      paperIds: ['pp6', 'pp7', 'pp8'],
      what: "Non-invasive early diagnosis through blood-based tests measuring disease-related proteins",
      why: "Current methods (PET scans, CSF analysis) are invasive, expensive, and not widely accessible. Blood tests enable population-level screening and earlier intervention (10-20 year window before symptoms).",
      how: [
        {
          id: 'm4',
          name: 'Plasma p-tau181',
          type: 'Protein biomarker',
          status: 'clinical-trials',
          maturityLevel: 4,
          paperIds: ['pp6', 'pp7'],
          effectiveness: '85% sensitivity, 90% specificity for AD detection',
          limitations: 'Requires validation across diverse ethnic groups, standardization needed'
        },
        {
          id: 'm5',
          name: 'Neurofilament light (NfL)',
          type: 'Protein biomarker',
          status: 'clinical-practice',
          maturityLevel: 5,
          paperIds: ['pp8'],
          effectiveness: 'Reflects neuronal damage, correlates with disease progression',
          limitations: 'Not specific to AD, elevated in other neurodegenerative diseases'
        },
        {
          id: 'm6',
          name: 'Multi-protein panels with ML',
          type: 'Machine learning + biomarkers',
          status: 'exploratory',
          maturityLevel: 2,
          paperIds: ['pp6'],
          effectiveness: 'Combined panels show >90% accuracy in pilot studies',
          limitations: 'Requires large validation studies, computational infrastructure'
        }
      ],
      gaps: [
        'Cost-effectiveness not yet proven at scale',
        'Lab standardization across sites needed',
        'Unclear if predicts treatment response'
      ],
      createdAt: '2024-01-10T10:00:00',
      lastUpdated: '2024-01-15T10:30:00',
      isFoundational: false,
      autoGenerated: true
    },
    {
      id: 'node2-2',
      title: 'AI-Based Screening',
      type: 'solution',
      parentId: 'node2',
      position: { x: 460, y: 350 },
      paperCount: 2,
      paperIds: ['pp8', 'pp9'],
      what: "Machine learning algorithms analyzing cognitive tests, imaging, or biomarker data for early detection",
      why: "Can identify subtle patterns invisible to human observers, enabling earlier intervention",
      how: [
        {
          id: 'm7',
          name: 'Retinal imaging + deep learning',
          type: 'Computer vision',
          status: 'exploratory',
          maturityLevel: 2,
          paperIds: ['pp9'],
          effectiveness: '80% accuracy detecting AD from retinal scans',
          limitations: 'Small sample sizes, needs prospective validation'
        }
      ],
      gaps: [
        'Interpretability of AI decisions limited',
        'Generalization across populations unclear'
      ],
      createdAt: '2024-01-10T10:00:00',
      lastUpdated: '2024-01-15T10:30:00',
      isFoundational: false,
      autoGenerated: true
    }
  ],
  connections: [
    {
      id: 'conn1',
      fromNodeId: 'node2-1',
      toNodeId: 'node2-2',
      type: 'complementary',
      explanation: 'Blood biomarkers provide data that AI screening algorithms analyze for diagnosis',
      evidencePaperIds: ['pp8', 'pp9'],
      strength: 'strong'
    },
    {
      id: 'conn2',
      fromNodeId: 'node1-1',
      toNodeId: 'node2-1',
      type: 'sequential',
      explanation: 'Understanding amyloid pathology enabled development of plasma p-tau biomarkers',
      evidencePaperIds: ['pp6', 'pp7'],
      strength: 'strong'
    },
    {
      id: 'conn3',
      fromNodeId: 'node1-2',
      toNodeId: 'node2-1',
      type: 'sequential',
      explanation: 'Tau pathology research led to blood-based tau biomarkers',
      evidencePaperIds: ['pp6'],
      strength: 'moderate'
    }
  ]
};

export const defaultTreeSettings: TreeSettings = {
  autoUpdate: true,
  buildFromAbstracts: true,
  buildFromCitations: true,
  buildFromHighlights: true,
  buildFromFullText: false,
  enabledBranches: ['Biology & Pathophysiology', 'Diagnosis & Detection', 'Treatment & Therapies', 'Caregiving & Quality of Life'],
  minPapersForSubBranch: 5,
  autoDetectRelationships: true,
  autoIdentifyGaps: true,
  suggestCrossLinks: true,
  flagContradictions: true,
  aiConfidenceThreshold: 'high',
  showLabels: 'always',
  showPaperCounts: true
};

export const branchOptions = [
  'Biology & Pathophysiology',
  'Diagnosis & Detection',
  'Treatment & Therapies',
  'Caregiving & Quality of Life',
  'Health Systems & Policy',
  'Ethics & Social Impact'
];
